name: 'Sync Action'
description: 'Sync v1 vault/assets onto v2 Beefy app'
author: 'chebiN'

inputs:
  GITHUB_TOKEN:
    description: 'Github token'
    required: true
  GITHUB_USER:
    description: 'Github user'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'